project_id = "ylhdznsfmvxfkhimglpi"

[functions.admin-user-management]
verify_jwt = true

[functions.reset-password]
verify_jwt = false

[functions.upload-to-drive]
verify_jwt = true

[functions.delete-from-drive]
verify_jwt = true

[functions.get-presigned-url-r2]
verify_jwt = true
